name = "roadster"
compatibility_date = "2025-06-12"

[assets]
directory = "./public"

routes = [
  { pattern = "roadster.mansoorbarri.com", custom_domain = true }
]

[env.production.vars]
HUGO_VERSION = "0.119.0"
